// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginRefreshTokenData, LoginRefreshTokenResponse, LoginTestTokenResponse, LoginLogoutData, LoginLogoutResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, MeetingsCreateMeetingResponse, MeetingsGetMyMeetingsData, MeetingsGetMyMeetingsResponse, MeetingsGetMeetingData, MeetingsGetMeetingResponse, MeetingsJoinMeetingData, MeetingsJoinMeetingResponse, MeetingsEndMeetingData, MeetingsEndMeetingResponse, MeetingsGetMessagesData, MeetingsGetMessagesResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, UtilsHealthzLiveResponse, UtilsHealthzReadyResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Refresh Token
     * Exchange a valid refresh token for a fresh access + refresh pair.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static refreshToken(data: LoginRefreshTokenData = {}): CancelablePromise<LoginRefreshTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/refresh',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Logout
     * Revoke a refresh token. Always returns 200 to avoid token-validity
     * oracles; if the supplied token is invalid the call is a no-op.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static logout(data: LoginLogoutData = {}): CancelablePromise<LoginLogoutResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/logout',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class MeetingsService {
    /**
     * Create Meeting
     * Create a new meeting. The authenticated user becomes the host (speaker).
     * Returns the meeting details including the shareable code.
     * @returns MeetingPublic Successful Response
     * @throws ApiError
     */
    public static createMeeting(): CancelablePromise<MeetingsCreateMeetingResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/meetings/',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Meetings
     * Get the current user's meeting history.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns MeetingsPublic Successful Response
     * @throws ApiError
     */
    public static getMyMeetings(data: MeetingsGetMyMeetingsData = {}): CancelablePromise<MeetingsGetMyMeetingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/meetings/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Meeting
     * Get meeting details by its shareable code.
     * @param data The data for the request.
     * @param data.code
     * @returns MeetingPublic Successful Response
     * @throws ApiError
     */
    public static getMeeting(data: MeetingsGetMeetingData): CancelablePromise<MeetingsGetMeetingResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/meetings/{code}',
            path: {
                code: data.code
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Join Meeting
     * Join an existing meeting by code. The joiner defaults to 'reader' role.
     * @param data The data for the request.
     * @param data.code
     * @param data.requestBody
     * @returns MeetingPublic Successful Response
     * @throws ApiError
     */
    public static joinMeeting(data: MeetingsJoinMeetingData): CancelablePromise<MeetingsJoinMeetingResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/meetings/{code}/join',
            path: {
                code: data.code
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * End Meeting
     * End a meeting. Only the host or a participant can end it.
     * @param data The data for the request.
     * @param data.meetingId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static endMeeting(data: MeetingsEndMeetingData): CancelablePromise<MeetingsEndMeetingResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/meetings/{meeting_id}/end',
            path: {
                meeting_id: data.meetingId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Messages
     * Get messages for a meeting. Supports cursor-based pagination.
     * The 'before' param is an ISO datetime for fetching older messages.
     * @param data The data for the request.
     * @param data.meetingId
     * @param data.limit
     * @param data.before
     * @returns MeetingMessagesPublic Successful Response
     * @throws ApiError
     */
    public static getMessages(data: MeetingsGetMessagesData): CancelablePromise<MeetingsGetMessagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/meetings/{meeting_id}/messages',
            path: {
                meeting_id: data.meetingId
            },
            query: {
                limit: data.limit,
                before: data.before
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User Me
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User Me
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * Combined liveness + readiness probe (kept for backward compatibility).
     *
     * Prefer the split `/healthz/live` and `/healthz/ready` endpoints in new
     * orchestrator configs.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
    
    /**
     * Healthz Live
     * Liveness probe — process is up and the event loop is responsive.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthzLive(): CancelablePromise<UtilsHealthzLiveResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/healthz/live'
        });
    }
    
    /**
     * Healthz Ready
     * Readiness probe — ML models are loaded and the app can serve traffic.
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static healthzReady(): CancelablePromise<UtilsHealthzReadyResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/healthz/ready'
        });
    }
}