// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Body for POST /api/v1/meetings/{code}/join.
 */
export type MeetingJoin = {
    role?: ParticipantRole;
};

export type MeetingMessagePublic = {
    id: string;
    meeting_id: string;
    sender_id: string;
    content: string;
    msg_type: MessageType;
    created_at?: (string | null);
};

/**
 * Paginated message list for GET /api/v1/meetings/{id}/messages.
 */
export type MeetingMessagesPublic = {
    data: Array<MeetingMessagePublic>;
    count: number;
    next_cursor?: (string | null);
};

export type MeetingParticipantPublic = {
    id: string;
    user_id: string;
    role: ParticipantRole;
    joined_at?: (string | null);
    left_at?: (string | null);
};

/**
 * Returned after creating or fetching a meeting.
 */
export type MeetingPublic = {
    id: string;
    code: string;
    status: MeetingStatus;
    host_id: string;
    created_at?: (string | null);
    started_at?: (string | null);
    ended_at?: (string | null);
    participants?: Array<MeetingParticipantPublic>;
};

/**
 * Paginated list of meetings (e.g., user history).
 */
export type MeetingsPublic = {
    data: Array<MeetingPublic>;
    count: number;
};

export type MeetingStatus = 'waiting' | 'active' | 'ended';

export type Message = {
    message: string;
};

export type MessageType = 'speech_transcript' | 'text_message' | 'gloss_translation' | 'gloss_input';

export type NewPassword = {
    token: string;
    new_password: string;
};

export type ParticipantRole = 'speaker' | 'reader';

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
};

export type RefreshTokenRequest = {
    refresh_token: string;
};

export type Token = {
    access_token: string;
    refresh_token?: (string | null);
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshTokenData = {
    requestBody?: (RefreshTokenRequest | null);
};

export type LoginRefreshTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginLogoutData = {
    requestBody?: (RefreshTokenRequest | null);
};

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MeetingsCreateMeetingResponse = (MeetingPublic);

export type MeetingsGetMyMeetingsData = {
    limit?: number;
    skip?: number;
};

export type MeetingsGetMyMeetingsResponse = (MeetingsPublic);

export type MeetingsGetMeetingData = {
    code: string;
};

export type MeetingsGetMeetingResponse = (MeetingPublic);

export type MeetingsJoinMeetingData = {
    code: string;
    requestBody?: MeetingJoin;
};

export type MeetingsJoinMeetingResponse = (MeetingPublic);

export type MeetingsEndMeetingData = {
    meetingId: string;
};

export type MeetingsEndMeetingResponse = (Message);

export type MeetingsGetMessagesData = {
    before?: (string | null);
    limit?: number;
    meetingId: string;
};

export type MeetingsGetMessagesResponse = (MeetingMessagesPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (unknown);

export type UtilsHealthzLiveResponse = (unknown);

export type UtilsHealthzReadyResponse = (unknown);